### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by charlesneimog** [pure-data/pd.cmake#7]
### `pd-lib-builder`

- [x] `PDDIR`: Root directory of 'portable' pd package. 

- [x] `PDINCLUDEDIR`: Directory where Pd API m_pd.h should be found, and other Pd header files. Overrides the default search path.

- [x] `PDBINDIR`: Directory where pd.dll should be found for linking (Windows only). Overrides the default search path.

- [x] `PDLIBDIR`: Root directory for installation of Pd library directories. 

- [x] `PDCMAKE_DIR`: Used for the user of `pd.cmake`. 

## `pd.cmake` path/directory

as suggested by @umlaeute 

``` cmake
set(PDCMAKE_DIR ${CMAKE_CURRENT_SOURCE_DIR} CACHE PATH "Path to pd.cmake")
include(${PDCMAKE_DIR}/pd.cmake)
```

## Cross Compiling

@umlaeute for this, maybe we could create some special variables, because if I understood your email, this is not enough:

```cmake
if ((CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64") AND LINUX)
```
at least for me, cross compiling need to be easy for Github Actions. `pd-else` for example, not support arm Linux yet.

## More TODOs

- [x] Not create files outside the build folder

**Comment by charlesneimog** [comment]
@umlaeute I have some thoughts regarding the default PDLIBDIR path configuration:

### Windows 

Currently, `pd-lib-builder` uses `%APPDATA%/Roaming/Pd` as the default path. However, this is a hidden folder on Windows, making it somewhat inconvenient to access (personal opinion). I believe it would be more intuitive to use `%HOME%/Documents/Pd/externals`, which is the default path for PureData. What do you think?

### Linux

For Linux, I suggest using `/home/Documents/Pd/externals`. In `pd-lib-builder`, the default path is /usr/local/lib/pd-externals, which requires sudo permissions to install. Using the home directory would simplify the installation process.

### Mac

For macOS, I would also recommend placing it in the Documents folder. However, I need access to an Apple machine to verify this configuration.

**Comment by charlesneimog** [comment]
## About `add_pd_external` function

I would simplify the `add_pd_external` function by reducing the number of arguments from three to two: one for the binary output name and one for the source code. Currently, the function takes three arguments: the library name, the binary output name, and the source code.

There's an issue with using the `~` character in the `add_library` function. We have two options to solve this:

Not allows the `~` char: `FATAL_ERROR` if the user set a output with the ~ character, something like: "You can't use the ~ character, replace it with _tilde."

Automatic Replacement: Automatically replace the ~ character, but this approach introduces more problems (as seen in the the test implementation in my repo's dev branch).

Current: `add_pd_external(library_name, binary_output_name, source_code)`
Suggested: `add_pd_external(binary_output_name, source_code)`

What do you think?

**Comment by umlaeute** [comment]
> What do you think?

mostly that these issues should be discussed separately, probably in https://github.com/pure-data/pd.cmake/discussions

**Comment by umlaeute** [comment]
moved this to:
- https://github.com/pure-data/pd.cmake/discussions/9
- https://github.com/pure-data/pd.cmake/discussions/11
